import 'dart:convert';
import 'dart:io';

import 'package:csv/csv.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../core/utils/formatters.dart';
import '../data/hive_database.dart';
import '../models/models.dart';

class ExportService {
  Future<File> exportCsv({
    required List<TransactionModel> transactions,
    required Map<String, CategoryModel> categories,
    required Map<String, AccountModel> accounts,
    required String currencyCode,
  }) async {
    final rows = <List<dynamic>>[
      [
        'Date',
        'Type',
        'Amount',
        'Category',
        'Account',
        'Note',
        'Tags',
        'Recurrence',
      ],
    ];

    for (final tx in transactions) {
      rows.add([
        DateFormat('yyyy-MM-dd').format(tx.date),
        tx.type.name,
        tx.amount.toStringAsFixed(2),
        categories[tx.categoryId]?.name ?? tx.categoryId,
        accounts[tx.accountId]?.name ?? tx.accountId,
        tx.note,
        tx.tags.join('|'),
        tx.recurrence.name,
      ]);
    }

    final csv = const ListToCsvConverter().convert(rows);
    final dir = await getTemporaryDirectory();
    final file = File(
      '${dir.path}/pocketflow_export_${DateTime.now().millisecondsSinceEpoch}.csv',
    );
    await file.writeAsString(csv);
    return file;
  }

  Future<File> exportPdfReport({
    required List<TransactionModel> transactions,
    required Map<String, CategoryModel> categories,
    required String currencyCode,
    required double income,
    required double expense,
    required double balance,
  }) async {
    final doc = pw.Document();
    final monthLabel = DateFormatters.monthYear(DateTime.now());

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'PocketFlow Monthly Report',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text(monthLabel, style: const pw.TextStyle(fontSize: 14)),
          pw.SizedBox(height: 16),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _pdfStat('Balance', MoneyFormatter.format(balance, currencyCode: currencyCode)),
              _pdfStat('Income', MoneyFormatter.format(income, currencyCode: currencyCode)),
              _pdfStat('Expenses', MoneyFormatter.format(expense, currencyCode: currencyCode)),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Transactions',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headers: const ['Date', 'Type', 'Category', 'Amount', 'Note'],
            data: transactions.take(40).map((tx) {
              return [
                DateFormat('MMM d').format(tx.date),
                tx.type.name,
                categories[tx.categoryId]?.name ?? '',
                MoneyFormatter.format(
                  tx.signedAmount,
                  currencyCode: currencyCode,
                  showSign: true,
                ),
                tx.note,
              ];
            }).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignment: pw.Alignment.centerLeft,
            cellStyle: const pw.TextStyle(fontSize: 9),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by PocketFlow — offline expense tracker',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File(
      '${dir.path}/pocketflow_report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
    await file.writeAsBytes(await doc.save());
    return file;
  }

  pw.Widget _pdfStat(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
        pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  Future<void> shareFile(File file, {String? subject}) async {
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        subject: subject ?? 'PocketFlow Export',
      ),
    );
  }
}

class BackupService {
  Future<File> createBackup() async {
    final payload = {
      'version': 1,
      'exportedAt': DateTime.now().toIso8601String(),
      'transactions':
          HiveDatabase.transactions.values.map((e) => e.toJson()).toList(),
      'categories':
          HiveDatabase.categories.values.map((e) => e.toJson()).toList(),
      'budgets': HiveDatabase.budgets.values.map((e) => e.toJson()).toList(),
      'accounts': HiveDatabase.accounts.values.map((e) => e.toJson()).toList(),
      'tags': HiveDatabase.tags.values.map((e) => e.toJson()).toList(),
      'budgetHistory':
          HiveDatabase.budgetHistory.values.map((e) => e.toJson()).toList(),
      'settings': HiveDatabase.settings.values.map((e) => e.toJson()).toList(),
    };

    final dir = await getApplicationDocumentsDirectory();
    final file = File(
      '${dir.path}/pocketflow_backup_${DateTime.now().millisecondsSinceEpoch}.json',
    );
    await file.writeAsString(const JsonEncoder.withIndent('  ').convert(payload));
    return file;
  }

  Future<void> restoreBackup(String jsonString) async {
    final data = jsonDecode(jsonString) as Map<String, dynamic>;
    await HiveDatabase.clearAll();

    for (final item in (data['categories'] as List<dynamic>? ?? [])) {
      final cat = CategoryModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.categories.put(cat.id, cat);
    }
    for (final item in (data['accounts'] as List<dynamic>? ?? [])) {
      final acc = AccountModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.accounts.put(acc.id, acc);
    }
    for (final item in (data['tags'] as List<dynamic>? ?? [])) {
      final tag = TagModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.tags.put(tag.id, tag);
    }
    for (final item in (data['transactions'] as List<dynamic>? ?? [])) {
      final tx = TransactionModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.transactions.put(tx.id, tx);
    }
    for (final item in (data['budgets'] as List<dynamic>? ?? [])) {
      final b = BudgetModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.budgets.put(b.id, b);
    }
    for (final item in (data['budgetHistory'] as List<dynamic>? ?? [])) {
      final h = BudgetHistoryModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.budgetHistory.put(h.id, h);
    }
    for (final item in (data['settings'] as List<dynamic>? ?? [])) {
      final s = AppSettingsModel.fromJson(item as Map<String, dynamic>);
      await HiveDatabase.settings.put('settings', s);
    }
  }

  Future<void> shareBackup(File file) async {
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        subject: 'PocketFlow Backup',
      ),
    );
  }
}
