class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.name,
    required this.symbol,
  });

  final String code;
  final String name;
  final String symbol;
}

/// ISO 4217 currency list used for settings selection.
const List<CurrencyInfo> kIsoCurrencies = [
  CurrencyInfo(code: 'USD', name: 'US Dollar', symbol: '\$'),
  CurrencyInfo(code: 'EUR', name: 'Euro', symbol: '€'),
  CurrencyInfo(code: 'GBP', name: 'British Pound', symbol: '£'),
  CurrencyInfo(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
  CurrencyInfo(code: 'CNY', name: 'Chinese Yuan', symbol: '¥'),
  CurrencyInfo(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
  CurrencyInfo(code: 'AUD', name: 'Australian Dollar', symbol: 'A\$'),
  CurrencyInfo(code: 'CAD', name: 'Canadian Dollar', symbol: 'C\$'),
  CurrencyInfo(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF'),
  CurrencyInfo(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$'),
  CurrencyInfo(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$'),
  CurrencyInfo(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$'),
  CurrencyInfo(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
  CurrencyInfo(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
  CurrencyInfo(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
  CurrencyInfo(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
  CurrencyInfo(code: 'MXN', name: 'Mexican Peso', symbol: '\$'),
  CurrencyInfo(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$'),
  CurrencyInfo(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
  CurrencyInfo(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
  CurrencyInfo(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
  CurrencyInfo(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ'),
  CurrencyInfo(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼'),
  CurrencyInfo(code: 'THB', name: 'Thai Baht', symbol: '฿'),
  CurrencyInfo(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
  CurrencyInfo(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
  CurrencyInfo(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
  CurrencyInfo(code: 'VND', name: 'Vietnamese Dong', symbol: '₫'),
  CurrencyInfo(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨'),
  CurrencyInfo(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
  CurrencyInfo(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£'),
  CurrencyInfo(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
  CurrencyInfo(code: 'PLN', name: 'Polish Zloty', symbol: 'zł'),
  CurrencyInfo(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
  CurrencyInfo(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
  CurrencyInfo(code: 'ILS', name: 'Israeli Shekel', symbol: '₪'),
  CurrencyInfo(code: 'CLP', name: 'Chilean Peso', symbol: '\$'),
  CurrencyInfo(code: 'ARS', name: 'Argentine Peso', symbol: '\$'),
  CurrencyInfo(code: 'COP', name: 'Colombian Peso', symbol: '\$'),
  CurrencyInfo(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/'),
  CurrencyInfo(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$'),
  CurrencyInfo(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
  CurrencyInfo(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
  CurrencyInfo(code: 'QAR', name: 'Qatari Riyal', symbol: '﷼'),
  CurrencyInfo(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك'),
  CurrencyInfo(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب'),
  CurrencyInfo(code: 'OMR', name: 'Omani Rial', symbol: '﷼'),
  CurrencyInfo(code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا'),
  CurrencyInfo(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs'),
  CurrencyInfo(code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs'),
  CurrencyInfo(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
  CurrencyInfo(code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵'),
  CurrencyInfo(code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.'),
  CurrencyInfo(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh'),
  CurrencyInfo(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh'),
  CurrencyInfo(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
  CurrencyInfo(code: 'ISK', name: 'Icelandic Krona', symbol: 'kr'),
  CurrencyInfo(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
  CurrencyInfo(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
  CurrencyInfo(code: 'RSD', name: 'Serbian Dinar', symbol: 'дин'),
  CurrencyInfo(code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج'),
  CurrencyInfo(code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت'),
  CurrencyInfo(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
  CurrencyInfo(code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل'),
  CurrencyInfo(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K'),
  CurrencyInfo(code: 'KHR', name: 'Cambodian Riel', symbol: '៛'),
  CurrencyInfo(code: 'LAK', name: 'Lao Kip', symbol: '₭'),
  CurrencyInfo(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮'),
  CurrencyInfo(code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm'),
  CurrencyInfo(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸'),
  CurrencyInfo(code: 'GEL', name: 'Georgian Lari', symbol: '₾'),
  CurrencyInfo(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼'),
  CurrencyInfo(code: 'AMD', name: 'Armenian Dram', symbol: '֏'),
  CurrencyInfo(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br'),
  CurrencyInfo(code: 'MDL', name: 'Moldovan Leu', symbol: 'L'),
  CurrencyInfo(code: 'ALL', name: 'Albanian Lek', symbol: 'L'),
  CurrencyInfo(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден'),
  CurrencyInfo(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
  CurrencyInfo(code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA'),
  CurrencyInfo(code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA'),
  CurrencyInfo(code: 'XCD', name: 'East Caribbean Dollar', symbol: '\$'),
  CurrencyInfo(code: 'BBD', name: 'Barbadian Dollar', symbol: '\$'),
  CurrencyInfo(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$'),
  CurrencyInfo(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT\$'),
  CurrencyInfo(code: 'BSD', name: 'Bahamian Dollar', symbol: '\$'),
  CurrencyInfo(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$'),
  CurrencyInfo(code: 'GYD', name: 'Guyanese Dollar', symbol: '\$'),
  CurrencyInfo(code: 'SRD', name: 'Surinamese Dollar', symbol: '\$'),
  CurrencyInfo(code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ\$'),
  CurrencyInfo(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K'),
  CurrencyInfo(code: 'WST', name: 'Samoan Tala', symbol: 'WS\$'),
  CurrencyInfo(code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T\$'),
  CurrencyInfo(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT'),
  CurrencyInfo(code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI\$'),
  CurrencyInfo(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨'),
  CurrencyInfo(code: 'SCR', name: 'Seychellois Rupee', symbol: '₨'),
  CurrencyInfo(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf'),
  CurrencyInfo(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.'),
  CurrencyInfo(code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP\$'),
  CurrencyInfo(code: 'BND', name: 'Brunei Dollar', symbol: 'B\$'),
  CurrencyInfo(code: 'AFN', name: 'Afghan Afghani', symbol: '؋'),
  CurrencyInfo(code: 'IRR', name: 'Iranian Rial', symbol: '﷼'),
  CurrencyInfo(code: 'YER', name: 'Yemeni Rial', symbol: '﷼'),
  CurrencyInfo(code: 'SYP', name: 'Syrian Pound', symbol: '£'),
  CurrencyInfo(code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د'),
  CurrencyInfo(code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.'),
  CurrencyInfo(code: 'SOS', name: 'Somali Shilling', symbol: 'Sh'),
  CurrencyInfo(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj'),
  CurrencyInfo(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk'),
  CurrencyInfo(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK'),
  CurrencyInfo(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK'),
  CurrencyInfo(code: 'BWP', name: 'Botswana Pula', symbol: 'P'),
  CurrencyInfo(code: 'NAD', name: 'Namibian Dollar', symbol: 'N\$'),
  CurrencyInfo(code: 'LSL', name: 'Lesotho Loti', symbol: 'L'),
  CurrencyInfo(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E'),
  CurrencyInfo(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT'),
  CurrencyInfo(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz'),
  CurrencyInfo(code: 'CVE', name: 'Cape Verdean Escudo', symbol: '\$'),
  CurrencyInfo(code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db'),
  CurrencyInfo(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D'),
  CurrencyInfo(code: 'GNF', name: 'Guinean Franc', symbol: 'FG'),
  CurrencyInfo(code: 'LRD', name: 'Liberian Dollar', symbol: '\$'),
  CurrencyInfo(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le'),
  CurrencyInfo(code: 'CDF', name: 'Congolese Franc', symbol: 'FC'),
  CurrencyInfo(code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw'),
  CurrencyInfo(code: 'BIF', name: 'Burundian Franc', symbol: 'FBu'),
  CurrencyInfo(code: 'KMF', name: 'Comorian Franc', symbol: 'CF'),
  CurrencyInfo(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar'),
  CurrencyInfo(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.'),
  CurrencyInfo(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡'),
  CurrencyInfo(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$'),
  CurrencyInfo(code: 'HNL', name: 'Honduran Lempira', symbol: 'L'),
  CurrencyInfo(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q'),
  CurrencyInfo(code: 'SVC', name: 'Salvadoran Colón', symbol: '\$'),
  CurrencyInfo(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$'),
  CurrencyInfo(code: 'HTG', name: 'Haitian Gourde', symbol: 'G'),
  CurrencyInfo(code: 'CUP', name: 'Cuban Peso', symbol: '\$'),
  CurrencyInfo(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U'),
  CurrencyInfo(code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲'),
  CurrencyInfo(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.'),
  CurrencyInfo(code: 'VEF', name: 'Venezuelan Bolívar', symbol: 'Bs'),
  CurrencyInfo(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ'),
  CurrencyInfo(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'),
  CurrencyInfo(code: 'KYD', name: 'Cayman Islands Dollar', symbol: '\$'),
  CurrencyInfo(code: 'BMD', name: 'Bermudian Dollar', symbol: '\$'),
  CurrencyInfo(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£'),
  CurrencyInfo(code: 'GIP', name: 'Gibraltar Pound', symbol: '£'),
  CurrencyInfo(code: 'SHP', name: 'Saint Helena Pound', symbol: '£'),
  CurrencyInfo(code: 'IMP', name: 'Isle of Man Pound', symbol: '£'),
  CurrencyInfo(code: 'JEP', name: 'Jersey Pound', symbol: '£'),
  CurrencyInfo(code: 'GGP', name: 'Guernsey Pound', symbol: '£'),
  CurrencyInfo(code: 'XPF', name: 'CFP Franc', symbol: '₣'),
  CurrencyInfo(code: 'XDR', name: 'IMF Special Drawing Rights', symbol: 'SDR'),
];

CurrencyInfo? findCurrency(String code) {
  try {
    return kIsoCurrencies.firstWhere((c) => c.code == code);
  } catch (_) {
    return null;
  }
}
